### ISSUE TITLE
Support `Clone` for Doc

### ISSUE THREAD

**Issue by namse** [y-crdt/y-crdt#179]
I found that yrs's Doc doesn't support Clone. 

In my case, `encode_state_as_update_v2` takes about 44ms so it blocked the client ui thread so I wanted to clone it to other context and encode in that context. It seems not possible for now because Doc doesn't support Clone.

Is there any plan for supporting Clone for Doc?

**Comment by Horusiath** [comment]
We explicitly removed cloning from `Block` - a core Yrs structure - because it was too tempting and easy to introduce it in places where it could result in hitting the performance. The only case where I could think about cloning documents being useful, would be tests, but even there using updates instead seems to be safer bet.

Could you share the use case you have in mind, that would benefit from adding Clone trait to Doc?

**Comment by namse** [comment]
My current code is not optimized so it's would cause a problem, I'm trying to optimize it. I will share the use case in detail if there is still a problem after optimization.

**Comment by namse** [comment]
@Horusiath I explored the problem further. I'm passing the Doc to another thread. So, I think `Send` should be implemented rather than `Clone`.
ycrdt is using Rc in `Rc<UnsafeCell<editor_core::yrs::store::Store>>` . Can we turn these things into `Arc`?

**Comment by Horusiath** [comment]
@namse this wouldn't change anything. We have plans to make strongly typed thread-safe read/write semantics for documents in the upcoming months, but so far what you can do is to put `Doc` behind `Arc<Mutext<Doc>>` and access everything through it.

**Comment by namse** [comment]
Actually I duck-taped with Arc<Mutex<Doc>> for now. I see, then I will close this issue and I hope that the strong type version you mentioned is well developed. I cheer for you!
