### ISSUE TITLE
XML Attribute Names Should Not Have Quotes in Text Representation

### ISSUE THREAD

**Issue by osanj** [y-crdt/y-crdt#204]
Hi, I am using y-crdt through [ypy](https://github.com/y-crdt/ypy). When converting an `YXmlElement` to a string, the names of the attributes have quotes, but only the values of the attributes should be in quotes. If you run the snippet below:
```python
from y_py import YDoc

doc = YDoc()
root = doc.get_xml_element("doc")
with doc.begin_transaction() as txn:
    item = root.push_xml_element(txn, "item")
    item.set_attribute(txn, "attr1", "123")

print(str(root))
```

You will get:
```
<UNDEFINED><item "attr1"="123"></item></UNDEFINED>
```
For it to be valid XML, it should be:
```
<UNDEFINED><item attr1="123"></item></UNDEFINED>
```

The issue seems to be here:
https://github.com/y-crdt/y-crdt/blob/0878462d49548a2db1b0e9e840ee8694fd00ac41/yrs/src/types/xml.rs#L95

---

Unrelated question:
Are there plans to make the tag of the root xml element mutable, so it can be assigned something different than `UNDEFINED`?

**Comment by Horusiath** [comment]
Thanks for noticing.

**Comment by osanj** [comment]
Sure, urw. Any input on this :point_down::slightly_smiling_face: 
> Are there plans to make the tag of the root xml element mutable, so it can be assigned something different than `UNDEFINED`?

**Comment by Horusiath** [comment]
At the moment no. The reason is that root level types are not really present in document block structure, they are inferred instead based on their children and user code calls. This means that Yjs didn't offered passing XML element tag if that XmlElement was at the root of a document. 

This wasn't big issue in case of Yjs, since Yjs didn't offer explicit way creating XmlElement as the root type (only XmlFragment, which is missing tag name). We're planning to introduce XmlFragments in Yrs with #202 . It was overlook on my side back then.

**Comment by osanj** [comment]
Ok, I already expected that this was not going to change, but thanks for the context! :nerd_face: 

Do you have an estimate for the implementation of the XmlFragment type? Are there any blockers or is it more about having time to get it done? Do you think it will be done in some weeks or rather some months?

**Comment by Horusiath** [comment]
I'd aim for this weekend ;)
