### ISSUE TITLE
Unexpected attribute changes lost after merging two docs

### ISSUE THREAD

**Issue by ArsnealX** [y-crdt/y-crdt#289]
**Description**
First, initialize two documents, A and B. A inserts text with different attributes, and then sends the changes to B. After that, A and B edit attributes at different locations, and then send changes to each other. The changes made by B will be lost.

**To Reproduce**
```rust
// yrs = "0.16.5"
// lib0 = "0.16.5"

use lib0::any::Any;
use std::rc::Rc;
use yrs::types::Attrs;
use yrs::{
    types::{
        text::{Diff, YChange},
        Value,
    },
    updates::{decoder::Decode, encoder::Encode},
    Doc, ReadTxn, StateVector, Text, Transact, Update,
};

fn send_updates(from: &Doc, to: &Doc) {
    let state_vector_encode = to.transact().state_vector().encode_v1();
    let update = from
        .transact()
        .encode_diff_v1(&StateVector::decode_v1(&state_vector_encode).unwrap());
    to.transact_mut()
        .apply_update(Update::decode_v1(&update).unwrap());
}

#[test]
fn reproduce() {
    let doc = Doc::new();
    let text = doc.get_or_insert_text("article");

    {
        let mut txn = doc.transact_mut();
        // insert "a" at index 0 with {"a": "a"}
        text.insert_with_attributes(
            &mut txn,
            0,
            "a",
            Attrs::from([(Rc::from("a"), Any::String(Box::from("a")))]),
        );
        // insert "b" at index 1 with {"a": "b"}
        text.insert_with_attributes(
            &mut txn,
            1,
            "b",
            Attrs::from([(Rc::from("a"), Any::String(Box::from("b")))]),
        );
    }

    let remote_doc = Doc::new();
    let remote_text = remote_doc.get_or_insert_text("article");

    send_updates(&doc, &remote_doc);

    // local doc: change the attribute value of the "a" from {"a": "a"} to {"a": "c"}
    {
        let mut txn = doc.transact_mut();
        text.format(
            &mut txn,
            0,
            1,
            Attrs::from([(Rc::from("a"), Any::String(Box::from("c")))]),
        );
    }

    // remote doc: change the attribute value of "b" from {"a": "b"} to {"a": "d"}.
    {
        let mut txn = remote_doc.transact_mut();
        remote_text.format(
            &mut txn,
            1,
            1,
            Attrs::from([(Rc::from("a"), Any::String(Box::from("d")))]),
        );
    }

    // merge
    send_updates(&doc, &remote_doc);
    send_updates(&remote_doc, &doc);

    /*
        expect:
        [
            {
                insert: "a",
                attributes: {"a": "c"}
            },
            {
                insert: "b",
                attributes: {"a": "d"}
            }
        ]
    */
    let expect = vec![
        Diff::<YChange>::new(
            Value::from("a"),
            Some(Box::from(Attrs::from([(
                Rc::from("a"),
                Any::String(Box::from("c")),
            )]))),
        ),
        // the expected attribute here is {"a": "d"} instead of {"a": "b"}
        Diff::<YChange>::new(
            Value::from("b"),
            Some(Box::from(Attrs::from([(
                Rc::from("a"),
                Any::String(Box::from("d")),
            )]))),
        ),
    ];

    /*
        unexpected: (both docs)
        [
            {
                insert: "a",
                attributes: {"a": "c"}
            },
            {
                insert: "b,
                attributes: {"a": "b"}
            }
        ]
    */

    assert_eq!(text.diff(&doc.transact(), YChange::identity), expect);
    assert_eq!(
        remote_text.diff(&remote_doc.transact(), YChange::identity),
        expect
    );
}
```

**Comment by Horusiath** [comment]
I've checked this, and while indeed it seems to be unexpected, it's seems to be aligned with Yjs behavior:

```js
const doc = new Y.Doc()
const text = doc.getText('article')
Y.transact(doc, () => {
    text.insert(0, 'a', {a:'a'})
    text.insert(1, 'b', {a:'b'})
})

const remoteDoc = new Y.Doc()
const remoteText =  remoteDoc.getText('article')

Y.applyUpdate(remoteDoc, Y.encodeStateAsUpdate(doc, Y.encodeStateVector(remoteDoc)))

text.format(0, 1, {a:'c'})
remoteText.format(1,1, {a:'d'})

Y.applyUpdate(remoteDoc, Y.encodeStateAsUpdate(doc, Y.encodeStateVector(remoteDoc)))
Y.applyUpdate(doc, Y.encodeStateAsUpdate(remoteDoc, Y.encodeStateVector(doc)))

const expected = [
    {insert:'a', attributes: {a:'c'}},
    {insert:'b', attributes: {a:'d'}},
]

console.log('local:', text.toDelta())
console.log('remote:', remoteText.toDelta())
/*

local: [
  { insert: 'a', attributes: { a: 'c' } },
  { insert: 'b', attributes: { a: 'b' } } 
]
remote: [
  { insert: 'a', attributes: { a: 'c' } },
  { insert: 'b', attributes: { a: 'b' } } 
]
*/
```

@dmonad it seems like a bug on both Yjs/Yrs sides.

**Comment by appflowy** [comment]
Hi @Horusiath.  I'm encountering the some issue. I am not sure it is the same case. Here are the test:

```rust

#[test]
fn apply_encode_update_test() {
  let doc_1 = Doc::new();
  let doc_2 = Doc::new();
  let root_map_1 = doc_1.get_or_insert_map("root");
  let root_map_2 = doc_2.get_or_insert_map("root");

  // root: { map:{ } }
  let mut map_1 = {
    let mut txn = doc_1.transact_mut();
    root_map_1.insert(&mut txn, "map", MapPrelim::<lib0::any::Any>::new())
  };
  // root: { map:{ } }
  let mut map_2 = {
    let mut txn = doc_2.transact_mut();
    root_map_2.insert(&mut txn, "map", MapPrelim::<lib0::any::Any>::new())
  };

  {
    let mut txn = doc_2.transact_mut();
    map_2.insert(&mut txn, "key_1", "a");
    map_2.insert(&mut txn, "key_2", "b");
  }

  let sv_1 = doc_1.transact().state_vector();
  let sv_update = doc_2.transact().encode_state_as_update_v1(&sv_1);
  {
    let mut txn = doc_1.transact_mut();
    let update = Update::decode_v1(&sv_update).unwrap();
    txn.apply_update(update);
  }

  let a = {
    let txn = doc_1.transact();
    root_map_1.to_json(&txn)
  };

  let b = {
    let txn = doc_2.transact();
    root_map_2.to_json(&txn)
  };

  println!("a: {}", a);
  println!("b: {}", b);
  assert_eq!(a, b);
}

```
The test results are unstable; sometimes they pass, and sometimes they fail. 
result 1:
a: {map: {}}
b: {map: {key_2: b, key_1: a}}

result 2:
a: {map: {key_2: b, key_1: a}}
b: {map: {key_2: b, key_1: a}}

**Comment by Horusiath** [comment]
@appflowy the supposed desync issue in your example is caused because you performed 1-way sync. If you sync in both directions, the result will be consistent.

When synchronizing updates, what happens is that a conflict has occurred - under the same key `"map"` two different maps where inserted - `map_1` and `map_2` are logically different entities. In order to resolve this conflict, an update that created a nested map from the client with higher ID will override the one that came from client with lower ID. If that happens, the overridden map will be tombstoned together with all its elements. 

The fact that it's not deterministic in you test comes from the fact, that `Doc::new()` generates random client ID for the document.

**Comment by appflowy** [comment]
> @appflowy the supposed desync issue in your example is caused because you performed 1-way sync. If you sync in both directions, the result will be consistent.
> 
> When synchronizing updates, what happens is that a conflict has occurred - under the same key `"map"` two different maps where inserted - `map_1` and `map_2` are logically different entities (in Yjs/Yrs only root types are logically equivalent by their name). In order to resolve this conflict, an update that created a nested map from the client with higher ID will override the one that came from client with lower ID. If that happens, the overridden map will be tombstoned together with all its elements.
> 
> The fact that it's not deterministic in you test comes from the fact, that `Doc::new()` generates random client ID for the document.

Thank you for your explanation. It saved my day. It works

**Comment by ArsnealX** [comment]
Hi @Horusiath ,

I hope you're doing well. I noticed this issue has been marked as "wontfix." I was wondering if you could kindly provide some insights into the reason behind this decision.

Thank you for your time.

**Comment by dmonad** [comment]
> I hope you're doing well. I noticed this issue has been marked as "wontfix." I was wondering if you could kindly provide some insights into the reason behind this decision.

Thanks for the ticket. I understand that you just want to improve the current implementation. But sometimes "perfect is the enemy of good". 

The issue describes unexpected behavior for formatting changes on Y.Text. I think it's fair to mark this as wontfix or close it, as any "fix" of that behavior would probably cause other issues. 

Some things I want to point out:

- It is impossible to preserve user-intend in all scenarios - especially for rich-text. Well.. unless you train some kind of AI that understands the document content and performs the merges (yes, this has been proposed..). 
- The provided example looks constructed. In practice, I assume that this issue is irrelevant. Especially since changes are merged in real-time, and the user can make the fix manually. There is actually a user study on rich-text editing that points out that users are highly unlikely to work on the same paragraph at the same time, if you have some kind of "shared cursor" feature. I try to fix things that are very relevant (I deem performance higher on the priority list). Otherwise, we would never be done.
- If you want offline editing, you must implement some kind of diff so the user can check the changes. There is no way around it.
- Formatting is hard. In practice, formatting attributes are overused, and we have to ensure they perform well. Now, we can make a tradeoff. We could add additional properties to all formatting items to fix the behavior. But that would increase complexity and worsen performance. `peritext`, for example, has better intention-preserving properties (it's definitely not perfect). But they can't garbage-collect that information well, and the document will blow up in scenarios where formatting is used extensively.

Unless the current behavior is unbearable (not just a slight annoyance in very rare cases), I'd actually suggest that we close this issue.

**Comment by ArsnealX** [comment]
Thank you for your thoughtful reply. Your insights make a lot of sense.
