### ISSUE TITLE
Question: Transaction origin for YTextEvent

### ISSUE THREAD

**Issue by fnlctrl** [y-crdt/y-crdt#306]
In Yjs, [event.transaction](https://github.com/yjs/yjs/blob/main/src/utils/Transaction.js#L95) exposes `origin` to tell whether a change was triggered locally or from remote, which is used in [y-quill](https://github.com/yjs/y-quill/blob/master/src/y-quill.js#L86)

However, in ywasm, [event.transaction](https://github.com/y-crdt/y-crdt/blob/main/ywasm/src/lib.rs#L1193) is not exposed to wasm-bindgen. This seems to block the usage of ywasm in the browser for quilljs

I don't know much about rust, is it possible to expose transaction on YTextEvent (and probably other events too)?

**Comment by Horusiath** [comment]
This issue will be solved as part of release v0.16.10 - each event will have an `origin` field inside. We won't expose the entire transaction object atm. since it will require bigger rework of how its done (usually transaction needs to be exposed to JS host by value, however in event callbacks this must be done by reference).
