### ISSUE TITLE
ffi, YDela release issue.

### ISSUE THREAD

**Issue by li-git** [y-crdt/y-crdt#308]
impl Drop for YDelta {
    fn drop(&mut self) {
        unsafe {
            if !self.attributes.is_null() {
                let len = self.attributes_len as usize;
                drop(Vec::from_raw_parts(self.attributes, len, len));
            }
            if !self.**insert**.is_null() {
                drop(Box::from_raw(self.insert));
            }
        }
    }
}

**Comment by xyzhangfred** [comment]
Some clarification:

We found a crash when using the Yrs FFI to C in our application, and after some investigation we believe we located the root cause as following, in this code:
```
impl Drop for YDelta {
    fn drop(&mut self) {
        unsafe {
            if !self.attributes.is_null() {
                let len = self.attributes_len as usize;
                drop(Vec::from_raw_parts(self.attributes, len, len));
            }
            if !self.attributes.is_null() {
                drop(Box::from_raw(self.insert));
            }
        }
    }
}
```
In the Drop implementation for YDelta, it appears there is a mistake in checking whether the self.insert is null. Instead, the self.attributes.is_null() check is repeated, which could lead to unexpected behavior if self.insert is null.

The correct implementation should look like this:

`impl Drop for YDelta {
    fn drop(&mut self) {
        unsafe {
            if !self.attributes.is_null() {
                let len = self.attributes_len as usize;
                drop(Vec::from_raw_parts(self.attributes, len, len));
            }
            if !self.insert.is_null() {
                drop(Box::from_raw(self.insert));
            }
        }
    }
}
`
And we were able to sovle the crash issue after making this change.

**Comment by Horusiath** [comment]
Thanks @xyzhangfred , I'll make a fix and release around Thursday/Friday.
