### ISSUE TITLE
Getting existing document root types

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/y-crdt#364]
The root types of a document are defined by the following methods:
- `get_or_insert_text(name)`
- `get_or_insert_map(name)`
- `get_or_insert_array(name)`
- etc.

Which respectively create a new `TextRef`, `MapRef` and `ArrayRef` if no structure under `name` exists, or return an existing structure if a structure under `name` exists with the same type, or reinterpret an existing structure with a different type.
It seems that when synchronizing with a remote document, one has to have prior knowledge of the document structure, and guess the root types, but the document cannot simply be "discovered" as it is received.
I'm wondering if there could be a document method for retrieving all the already existing root types?

**Comment by Horusiath** [comment]
Yrs has a `Transaction::root_refs` method that returns an iterator over keys+nodes of all root types. However atm. it will fail if you iterate it over a root type that was not defined locally (ie. because this root type was defined by remote update). The https://github.com/y-crdt/y-crdt/pull/357 is going to fix it, but it's not released yet.
