### ISSUE TITLE
[yrs] Not the result the doc expected.

### ISSUE THREAD

**Issue by mr04vv** [y-crdt/y-crdt#413]
I have two docs and made three changes to one of them.
And when I applied each update to the other doc in a different order, the results were not what I expected.

Is this a glitch? Or am I using it wrong?

I am curious because yjs shows the expected results.

```
use std::sync::{Arc, Mutex};

use yrs::updates::decoder::Decode;
use yrs::{Doc, Map, Transact, TransactionMut, Update, UpdateEvent, WriteTxn};
use yrs::types::ToJson;

fn main() {
    let doc1 = Doc::new();
    
    let v: Arc<Mutex<Vec<Vec<u8>>>> = Arc::new(Mutex::new(Vec::new()));
    let v_clone = Arc::clone(&v);

    let listener = move |_: &TransactionMut, e: &UpdateEvent| {
        v_clone.lock().unwrap().push(e.update.clone());
    };
 

    let sub = doc1.observe_update_v1(listener);
    
    let map = doc1.get_or_insert_map("map");
    
    {
        let mut txn = doc1.transact_mut();
        map.insert(&mut txn, "a", 1);
        txn.commit();
    }

    {
        let mut txn = doc1.transact_mut();
        map.insert(&mut txn, "a", 1.1);
        txn.commit();
    }

    {
        let mut txn = doc1.transact_mut();
        map.insert(&mut txn, "b", 2);
        txn.commit();
    }

    {
        let mut txn = doc1.transact_mut();
        let m = txn.get_or_insert_map("map");
        println!("doc1: {:?}", m.to_json(&txn)); // {a: 1.1, b: 2}
    }
    
    drop(sub);
    
    let locked_updates = v.lock().unwrap();

    let doc2 = Doc::new();

    {
        let mut txn = doc2.transact_mut();
        let update = Update::decode_v1( &locked_updates[0] ).unwrap();
        txn.apply_update(update);
        let update2 = Update::decode_v1( &locked_updates[2] ).unwrap();
        txn.apply_update(update2);
        let update3 = Update::decode_v1( &locked_updates[1] ).unwrap();
        txn.apply_update(update3);
        txn.commit();
    }

    {
        let mut txn = doc2.transact_mut();
        let m = txn.get_or_insert_map("map");
        println!("doc2: {:?}", m.to_json(&txn)); // expected {a: 1.1, b: 2} but actual {a: 1.1}
    }

}
```
doc1: { a: 1.1, b: 2 }
doc2: { a: 1.1 } // expected { a: 1.1, b: 2 }

**Comment by Horusiath** [comment]
Thanks for noticing. This issue has already been fixed and merged to main. It will be included in the next release.

**Comment by mr04vv** [comment]
Thank you! 🎉

**Comment by cacosandon** [comment]
Hey @Horusiath! I am using [ypy](https://github.com/y-crdt/ypy) and noticed this problem, because we do some checks on every update and rejecting on the server the ones that have missing keys.

Is there any other workaround? When is the next release?

Thanks 🙏

**Comment by cacosandon** [comment]
Also, there is an [issue in Yjs](https://github.com/yjs/yjs/issues/461) because of incomplete states when updates are not in order and so there are `pendingStructs` (and so if you don't receive the missing update, the key is deleted forever and I think the document is corrupted?). Do you know what is the best option to handle this server side?

**Comment by Horusiath** [comment]
@cacosandon sorry for the late response. In general out-of order issues and missing data is signal for failing connection. In such case you should probably restart connection and trigger sending updates from the last known Doc's state vector. Since yrs v0.18.x, you can also detect if updates have not been fully integrated via [Store::pending_update](https://docs.rs/yrs/latest/yrs/struct.Store.html#method.pending_update):

```rust
let mut doc = Doc::new();
let mut txn = doc.transact_mut();
txn.apply_update(update);
if txn.store().pending_update().is_some() {
  // update was not fully applied, send request to reapply
  send_request(txn.state_vector());
}
```

This is probably not yet implemented in y-py, so if you cannot wait, you can try to simply restart connection ie. every minute or so.

**Comment by cacosandon** [comment]
Thank you @Horusiath! We ended doing what you said; restarting the connection and re-sync. This works perfectly :)
