### ISSUE TITLE
Serialization support?

### ISSUE THREAD

**Issue by audunhalland** [y-crdt/y-crdt#495]
Hi, when using y-crdt in a server application, I think it would be a good idea to have some kind of serialization and deserialization support:

* Servers should be able to restart with their state preserved.
* Typically, the server is working on synchronizing the most recent document changes. Older changes could be less relevant after all clients have synced. Therefore it could make sense to have only part of the model in working memory at a given time, while it would be possible to retrieve the full working history from persistent storage.

I have no deep knowledge of y-crdt, I have used it only briefly for initial research. But these were the questions that popped up! Also, thanks for working on this really cool project.

**Comment by Horusiath** [comment]
We're still discussing the sponsorship, that would let us write a wariant of yrs that would be persistent-first rather than being in-memory database. 

At the current moment, there are crates that support flushing document state and updates to persistent key-value stores like [LMDB](https://crates.io/crates/yrs-lmdb) or [RocksDB](https://crates.io/crates/yrs-rocksdb). There's also [a Postgres extension](https://supabase.com/blog/postgres-crdt) to support Yrs data types natively. Kevin is also working on pro-version of [y-redis](https://github.com/yjs/y-redis) backend.

With current design, it's simply not feasible to have parts of document loaded in memory. If the document is to big to fit in, this usually indicates either:
1. There's some pathological write patterns happening ie. non-sequential updates (writing to different entries), blind writes (overriding existing entry with the same value) or keeping data that's doesn't require conflict resolution in Doc.
2. Document needs partitioning. This is what subdocs feature is for - basically you can cross-reference documents and load/unload them on demand.
