### ISSUE TITLE
Implementing Send Trait for the Doc Type

### ISSUE THREAD

**Issue by GarettCooper** [y-crdt/y-crdt#68]
Hi, I've been experimenting with the use of Yrs for a personal project as it meets all of my CRDT requirements. However, the Doc type being `!Send` is a signficant barrier for adoption, as I would need to significantly restructure the multi-threaded asynchronous context of my application to work around it. I'm exploring alternatives like reconstructing the Doc from a shared encoded State Vector and the alternative update API, but it would be much easier to wrap an `Arc<Mutex<_>>` around the Doc.

I haven't delved into the code of Yrs too deeply, but the use of the `Rc<UnsafeCell<_>>` wrapper around `Store` seems like the most significant barrier to thread-safety. It looks like this abstraction has yet to be set in stone based on #4, so I'm wondering if it could be adapted to be `Send` at the same time.

**Comment by Horusiath** [comment]
Single thread-ness was one of the design decisions made in the early days. Yrs is client-oriented library, and its primary use case is on the edge devices, operated by a single actor at the time. You can naturally use `Arc<Mutex<Doc>>` + ensure transactions to not outlive acquired document guard for scenarios that need it. 

In the past Store was simply hidden behind RefCell and transaction was basically using a `Transaction<'txn> { store: RefMut<'txn, Store> }` scheme, but that proved difficult to work with certain class of scenarios like using transaction as parameters in subscriber callbacks for WASM and C FFI. On the other hand hiding store behind `Rc<RefCell<_>>` and borrowing from it put a visible overhead - as Yrs internals often need to borrow store from a transaction multiple times in order to satisfy borrow checker demands (at least in the current implementation) - which seemed to be non-justifiable for something that is supposed to work in single-thread context anyway.

It's quite possible that we'll come back and improve this design in the future eg. splitting transactions between read-only and read-write ones with support of `RefCell` API - but at the moment it's not a priority.

**Comment by GarettCooper** [comment]
> You can naturally use Arc<Mutex<Doc>> + ensure transactions to not outlive acquired document guard for scenarios that need it.

Unforunately you can't which is the root of my issue. The following code would meet my needs just fine, but doesn't compile since `Doc` isn't send:
```rust
use std::sync::{Arc, Mutex};
use yrs::{Array, Doc, Map};

pub fn create_map(map_id: &str) {
    let mut doc = Arc::new(Mutex::new(Doc::new()));
    let doc_clone = doc.clone();
    tokio::spawn(async move {
        let mut locked_doc = doc_clone.lock().unwrap();
        let mut txn = locked_doc.transact();
        let map = txn.get_map(map_id);
        map.insert(&mut txn, "key1", "value1");
        txn.commit();
    });
}
```

I've arrived at the following solution for implementing `Send` which I _think_ is sound, but I'm not certain:

```rust
use std::marker::PhantomData;
use std::ops::{Deref, DerefMut};
use std::sync::{Arc, Mutex};
use yrs::{Array, Doc, Map};

pub fn create_map(map_id: &str) {
    let mut doc = Arc::new(Mutex::new(UnsafeSend(Doc::new())));
    let doc_clone = doc.clone();

    let id = map_id.to_string();

    tokio::spawn(async move {
        let mut locked_doc = doc_clone.lock().unwrap();
        let mut txn = locked_doc.transact();
        let mut txn_lifetime = LifetimeProtector::new(&locked_doc, txn);
        let map = txn_lifetime.get_map(&id);
        map.insert(&mut txn_lifetime, "key1", "value1");
        std::mem::drop(locked_doc);
        txn_lifetime.commit(); // <-- This is a compile error
    });
}

struct UnsafeSend<T>(T);

unsafe impl<T> Send for UnsafeSend<T> {}

impl<T> Deref for UnsafeSend<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

struct LifetimeProtector<'a, T, I>(PhantomData<&'a T>, I);

impl<'a, T, I> LifetimeProtector<'a, T, I> {
    fn new(_reference: &'a T, inner: I) -> Self {
        Self(PhantomData, inner)
    }
}

impl<Doc, I> Deref for LifetimeProtector<'_, Doc, I> {
    type Target = I;

    fn deref(&self) -> &Self::Target {
        &self.1
    }
}

impl<Doc, I> DerefMut for LifetimeProtector<'_, Doc, I> {
    fn deref_mut(&mut self) -> &mut I {
        &mut self.1
    }
}

```
It's not exactly ergonomic, so having official support for this use case would be much appreciated.

**Comment by Horusiath** [comment]
Thanks, I see your point. We'll address this issue.
